atom_data_field: "atom"
bond_data_field: "etype"
classification_metric_name: "roc_auc"
regression_metric_name: "r2"
num_epochs: 500
patience: 50
batch_size: 2048
mode: "higher"
lr: 0.0001
weight_decay: 0.00001
in_feats: 40
rgcn_hidden_feats:
  - 64
  - 64
rgcn_drop_out: 0.2
loop: true
classifier_hidden_feats: 64
drop_out: 0.2
task_name: "admet_52_CYP2C19"
select_task_list:
  - "Carcinogenicity"
  - "Ames Mutagenicity"
  - "Respiratory toxicity"
  - "Eye irritation"
  - "Eye corrosion"
  - "Cardiotoxicity1"
  - "Cardiotoxicity5"
  - "Cardiotoxicity10"
  - "Cardiotoxicity30"
  - "CYP1A2"
  - "CYP2C19"
  - "CYP2C9"
  - "CYP2D6"
  - "CYP3A4"
  - "NR-AR"
  - "NR-AR-LBD"
  - "NR-AhR"
  - "NR-Aromatase"
  - "NR-ER"
  - "NR-ER-LBD"
  - "NR-PPAR-gamma"
  - "SR-ARE"
  - "SR-ATAD5"
  - "SR-HSE"
  - "SR-MMP"
  - "SR-p53"
  - "PAMPA_NCATS"
  - "HIA_Hou"
  - "Pgp_Broccatelli"
  - "Bioavailability_Ma"
  - "BBB_Martins"
  - "CYP2C9_Substrate_CarbonMangels"
  - "CYP2D6_Substrate_CarbonMangels"
  - "CYP3A4_Substrate_CarbonMangels"
  - "hERG_Karim"
  - "DILI"
  - "Skin Reaction"
  - "ClinTox"
select_task_index: []
classification_list: []
regression_list: []
all_task_list:
  - "Carcinogenicity"
  - "Ames Mutagenicity"
  - "Respiratory toxicity"
  - "Eye irritation"
  - "Eye corrosion"
  - "Cardiotoxicity1"
  - "Cardiotoxicity5"
  - "Cardiotoxicity10"
  - "Cardiotoxicity30"
  - "CYP1A2"
  - "CYP2C19"
  - "CYP2C9"
  - "CYP2D6"
  - "CYP3A4"
  - "NR-AR"
  - "NR-AR-LBD"
  - "NR-AhR"
  - "NR-Aromatase"
  - "NR-ER"
  - "NR-ER-LBD"
  - "NR-PPAR-gamma"
  - "SR-ARE"
  - "SR-ATAD5"
  - "SR-HSE"
  - "SR-MMP"
  - "SR-p53"
  - "PAMPA_NCATS"
  - "HIA_Hou"
  - "Pgp_Broccatelli"
  - "Bioavailability_Ma"
  - "BBB_Martins"
  - "CYP2C9_Substrate_CarbonMangels"
  - "CYP2D6_Substrate_CarbonMangels"
  - "CYP3A4_Substrate_CarbonMangels"
  - "hERG_Karim"
  - "DILI"
  - "Skin Reaction"
  - "ClinTox"
  - "Acute oral toxicity (LD50)"
  - "LC50DM"
  - "BCF"
  - "LC50"
  - "IGC50"
  - "Caco2_Wang"
  - "Lipophilicity_AstraZeneca"
  - "Solubility_AqSolDB"
  - "HydrationFreeEnergy_FreeSolv"
  - "PPBR_AZ"
  - "VDss_Lombardo"
  - "Half_Life_Obach"
  - "Clearance_Hepatocyte_AZ"
  - "Clearance_Microsome_AZ"
task_class: ""
bin_path: "./data/admet_52.bin"
group_path: "./data/admet_52_group.csv"